### ISSUE TITLE
'bash scripts/prepare_checkpoints.sh' exists problem.

### ISSUE THREAD

**Issue by FYZ8** [Jumabek/LITE#2]
/home/xxx/anaconda3/envs/LITE/lib/python3.10/site-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Error:

	HTTPSConnectionPool(host='drive.google.com', port=443): Max retries
	exceeded with url: /uc?id=1L4gnCbkmvGB6HbPPs1YK8O2fERBS-Xvn (Caused by
	ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at
	0x7f00a17d1cf0>, 'Connection to drive.google.com timed out. (connect
	timeout=None)'))

To report issues, please visit https://github.com/wkentaro/gdown/issues.
Failed to download checkpoints.zip

**Comment by dilshod-obidov** [comment]
Thank you for reaching out!
The issue is probably because of download limits of gdown used in the script.
To avoid this, I updated README.md with instructions to prepare checkpoints in alternative way.
