### ISSUE TITLE
how to reproduce results in paper

### ISSUE THREAD

**Issue by trongldwork** [Jumabek/LITE#3]
I want to reproduce your results in paper but you havent write setting setup on its, can you provide me what settings you use for like detector model, threshold,...etc

**Comment by dilshod-obidov** [comment]
Thank you for reaching out. 
Experiments use YOLOv8m, with a confidence thresh-
old of 0.25 and image resolution of 1280, other settings are configured in code of our repository.
Also,  
For MOT17, the FRCNN version of ground truth is
used. For KITTI and VIRAT-S, only pedestrian and person classes are evaluated.
Experiments are conducted on: Intel Core i9-12900K at 5.2 GHz, NVIDIA GeForce RTX 3090 with 24 GB
VRAM, 64 GB DDR4 at 3200 MHz. FPS benchmarks measured with no other
significant processes running, using the first video sequence of each dataset.
