### ISSUE TITLE
Is the demo still working?

### ISSUE THREAD

**Issue by hsuanguo** [Jumabek/LITE#5]
Got this error 

```bash
 python lite_deepsort_demo.py --source demo/VIRAT_S_010204_07_000942_000989.mp4
```

```
    x = x[xc[xi]]  # confidence
IndexError: The shape of the mask [92, 160] at index 0 does not match the shape of the indexed tensor [144, 160, 92] at index 0
```

If I change the `ultralytics` to  `4c5b1bfaa1be09bba30f14a205c85eb2cad5ff7b`, it does ran but there is no track output at all.

Is there anything not synced yet?

Many thanks

**Comment by dilshod-obidov** [comment]
Thank you  for reaching out!

The mentioned issue is fixed. Try again after `git clone https://github.com/humblebeeintel/ultralytics.git` or pulling updates.

Feel free to reopen the issue, if there the issue still persists
